---
- hosts: all
  become: true
  user: ubuntu
  tasks:
  - name: change the ownership permissions
    command: sudo chown -R ubuntu:ubuntu /home/ubuntu/

  #- name: delete already existing files
   # command: sudo rm -rf /home/ubuntu

  - name: execute command
    command: "{{item}}"
    with_items:
      - apt  update
      - apt install python3-pip python3-dev nginx git -y
      
  - name: clone a public repository
    command: git clone https://github.com/ani1203/learnDjango.git
    
  - name: changing ownership of chatapp 
    command: sudo chown -R ubuntu:ubuntu /home/ubuntu/learnDjango

  - name: copy requirements.txt file 
    copy: 
      src: /etc/ansible/playbooks/requirements.txt
      dest: /home/ubuntu/learnDjango

  - name: install virtualenv
    pip: name=virtualenv state=latest virtualenv_command=virtualenv

  - name: creating virtualenv
    command: virtualenv /home/ubuntu/venv

  - name: activating environment
    command: source /home/ubuntu/venv/bin/activate
    command: /home/ubuntu/venv/bin/pip install -r /home/ubuntu/learnDjango/requirements.txt

  - name: Install gunicorn
    pip: name=gunicorn state=latest virtualenv=/home/ubuntu/venv
    
  - name: execute command
    command: "{{item}}"
    with_items:
      - apt  update
      - pip3 install Django==2.1.3
      - pip3 install channels
        ###  pip3 install psycopg2
      - pip3 install django bcrypt django-extensions      
     
  - name: copy gunicorn service file
    copy:
       src: /etc/ansible/playbooks/gunicorn.service
       dest: /etc/systemd/system
  
  - name: execute command
    command: "{{item}}"
    with_items:
      - systemctl daemon-reload
      - systemctl start gunicorn
      - systemctl enable gunicorn

  - name: creating symbolic link
    command: sudo ln -s /etc/nginx/sites-available/learnDjango /etc/nginx/sites-enabled
 
  - name: copy nginx file
    copy:
       src: /etc/ansible/playbooks/learnDjango
       dest: /etc/nginx/sites-available
  # - name: Create symbolic link 
   # file:
    # src: /etc/nginx/sites-available/learnDjango
    # dest: /etc/nginx/sites-enabled
    # state: link
    #notify: nginx reload

      
  - name: delete file from sites-enabled
    become: true
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent    
             
  - name: restart service nginx
    systemd:
      state: restarted
      name: nginx

  - name: restart service gunicorn again
    systemd:
      state: restarted
      name: gunicorn


