---
- hosts: all
  become: true  
  tasks:
  - name: execute command 
    command: "{{item}}"
    with_items: 
      - apt  update
      - apt install python3-pip python3-dev nginx git -y  
      - pip3 install Django==2.1.3
      - pip3 install channels
      -  pip3 install psycopg2
 
